### ISSUE TITLE
How to run this project

### ISSUE THREAD

**Issue by 1553545365** [Laiqingsi/CLOCs_LQS#1]
您好，非常感谢您的工作，我也希望能在OpenPCDet工程下完成对CLOCs的复现，请问能不能更具体的描述一下您的项目代码要如何运行？数据要如何放置？

Hello, thank you very much for your work, and I would like to complete the CLOCs replication under the OpenPCDet project. Can you describe more specifically how can I run your project code works? How to place the KITTI data?

**Comment by Laiqingsi** [comment]
Hi, thank you for your attention. CLOCs does not rely on KITTI data, it relies on detection results, so you just need to finish detection task by follow OpenPCDet. The readme file has described how to run this project, you can follow it. But maybe readme does not mention one point that you need to add code path to your ".bashrc", otherwise something will be wrong. Hope this can help you. #1
